schema_version: 1

context:
  name: mergechannels
  version: "0.7.0"

package:
  name: ${{ name|lower }}
  version: ${{ version }}

source:
  url: https://pypi.org/packages/source/${{ name[0] }}/${{ name }}/mergechannels-${{ version }}.tar.gz
  sha256: 022538ecc97a92f52fd527a1a9ced11750abe69e4152162bb37f2fbf064032c1

build:
  number: 0
  script:
    - cargo-bundle-licenses --format yaml --output ./THIRDPARTY.yml
    - ${{ PYTHON }} -m pip install . -vv --no-deps --no-build-isolation

requirements:
  build:
    - if: build_platform != host_platform
      then:
        - python
        - cross-python_${{ host_platform }}
    - ${{ compiler('rust') }}
    - ${{ stdlib("c") }}
    - cargo-bundle-licenses
  host:
    - python
    - maturin >=1.8,<2.0
    - pip
  run:
    - python
    - numpy >=1.25

tests:
  - python:
      imports:
        - mergechannels
      pip_check: true

about:
  homepage: https://github.com/zacswider/mergechannels
  summary: Apply and merge colormaps
  description: |
    A simple, fast, and memory-efficient library for applying and blending 
    colormaps to images. Written in Rust with Python bindings via PyO3/maturin.
    Includes many FIJI lookup tables and supports external colormaps from 
    matplotlib and cmap. Fully compatible with free-threaded Python.
  license: MIT
  license_file:
    - LICENSE
    - assets/christ_luts/LICENSE
    - assets/christ_luts/NOTICE
    - THIRDPARTY.yml
  repository: https://github.com/zacswider/mergechannels

extra:
  recipe-maintainers:
    - zacswider
